version: '3.4'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: la_comte
      POSTGRES_PASSWORD: sasha112859
      POSTGRES_DB: lab6
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    logging:
      options:
        max-size: "500k"
        max-file: "10"
volumes:
  postgres_data:
    name: demo-postgres