spring:
  application:
    name: Lab6_REST_API
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/lab6?currentSchema=public
    username: la_comte
    password: sasha112859
    driverClassName: org.postgresql.Driver
  jpa:
    database: postgresql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8090